services:

  postgres:
    image: "postgres:18-trixie"
    user: "543000:543000"
    container_name: "postgres-passwords"
    restart: "on-failure"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /var/log/postgres-passwords:/var/log/postgresql:rw
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    networks:
      postgres_network:
        ipv4_address: "172.18.102.2"
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 3


volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.102.0/24
          gateway: 172.18.102.1
