listen_addresses = '172.18.102.2'
port = 5432

# Depends on your CPU capabilities
max_parallel_workers = 4
max_parallel_workers_per_gather = 2
max_parallel_maintenance_workers = 4
max_connections = 50
# work_mem ≈ RAM MB / (average_heavy_parallel_queries × 3)
# for our case it will be 4000 / (3 x 3)
work_mem = '445MB'

# For the SSD. for the HDD consider having 4.0 here
random_page_cost = 1.1

logging_collector = on
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age = '14d'
log_rotation_size = '1GB'
log_min_duration_statement = 1000 # Logs all operations longer than 1s
